

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true